# Generated by Django 3.0.4 on 2020-03-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='valor_market_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
