# Generated by Django 3.0.3 on 2020-03-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ValorMarket',
            field=models.IntegerField(default=0, verbose_name='Monedas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Fecha publicación'),
        ),
    ]
