# Generated by Django 3.0.3 on 2020-03-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200306_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='Saldo',
            field=models.IntegerField(default=1, verbose_name='Monedas'),
            preserve_default=False,
        ),
    ]
