# Generated by Django 3.0.4 on 2020-03-13 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_choice_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='completed_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
